### ISSUE TITLE
Disqus not loading

### ISSUE THREAD

**Issue by dixonge** [chipsenkbeil/grid-side#20]
After fixing my compile error, I can see that the disqus shortname is set in config.toml and is being pushed to my source repo on github. But when I run `hugo -d` and compile the site to its own directory the resulting html files do not contain the disqus code. It seems like the 'if' statement in disqus.html isn't seeing that the disqus shortname has been set.

**Comment by chipsenkbeil** [comment]
Hm, odd. I'll have to take a look at that.

One thing to note is that I run Hugo using `$(GOPATH)/bin/hugo --theme="grid-side"` from my personal website's project: https://github.com/chipsenkbeil/senkbeil.org There is no `-d` option in my build. I'm using Travis to build (via that command) whenever I push to the repository and then push out the changes to here: https://github.com/chipsenkbeil/chipsenkbeil.github.io

My site has comments working. Keep in mind that comments are only shown for posts, IIRC.

**Comment by dixonge** [comment]
I've got the theme set in config.toml - can't imagine that would make a difference though.

I have another site w/ another theme and disqus works, so I may change my build process and test that out. The other site is a project page w/ gh-pages branch as a subtree, mirroring off of public. I'm having this Disqus issue w/ two sites, so I'll have to try the subtree on the one which is a project page, not my main blog on dixonge.github.io .

I even tried changing some capitalization of disqusShortname vs DisqusShortname in both the disqus.html file and the config file. All changes produced errors on build.

**Comment by dixonge** [comment]
Tried a few other things tonight, none worked. I ended up just manually inserting Disqus code into the single.html partial.

**Comment by dixonge** [comment]
This is an OLD issue, so I'll update and close:

1 - Disqus doesn't load on localhost, complaining of no javascript. This could be a browser issue, or that Disqus just doesn't work on localhost...
2 - Disqus loads just fine on my current site, pushed to Github then built and served via Netlify
