### ISSUE TITLE
Option to remove 'post' from Main menu

### ISSUE THREAD

**Issue by dixonge** [chipsenkbeil/grid-side#22]
Although I have left all of my blog posts as individual markdown files under /post/ I have customized my menu, mainly using category to organize my blog posts. So I don't need a menu item for 'post' - but I can't find where that is being inserted, other than perhaps some default Hugo functionality. Is this something that I need to change in the theme, or is it in the main Hugo code?

**Comment by chipsenkbeil** [comment]
Did you set `SectionPagesMenu = "main"` like in the docs [here](http://gohugo.io/extras/menus/#section-menu-for-the-lazy-blogger:4044c7430755cd64e5b7c48e836cea57)? That injects all of the sections as menu items. If you look at my site [here](https://github.com/chipsenkbeil/senkbeil.org/blob/master/config.toml#L34), you'll see that I am explicitly setting individual menu items. If you do it that way, you shouldn't have your post section appear unless you set it yourself.

**Comment by dixonge** [comment]
ok, so it's an either/or option? I just commented out the 'SectionPagesMenu' line, and now my menu looks like I expected! Three main menu items, one with 3-4 sub-menus. Perfect!

**Comment by chipsenkbeil** [comment]
Yep. Either/or scenario. That option is meant for those that want a quick menu based on their sections. For more in-depth menus (and nested menus), you need to explicitly define it as they define in the documentation. Since it works for you now, going to close the issue. :)
