### ISSUE TITLE
youtube shortcode

### ISSUE THREAD

**Issue by magomimmo** [chipsenkbeil/grid-side#23]
Hi, first of all thanks so much for sharing your hugo theme. 

I'm using `{{% youtube bbbbbb %}}` shortcode inside contents. Is there a way to add a `loop` flag inside that shortcode? 

Thanks

**Comment by chipsenkbeil** [comment]
It could, but it doesn't have that listed in the base shortcode. You can see the source here: https://github.com/chipsenkbeil/grid-side/blob/master/layouts/shortcodes/youtube.html

I'm always open to PRs. :)

**Comment by magomimmo** [comment]
Thanks. I discovered this note on loop:

https://developers.google.com/youtube/player_parameters#loop

which makes the UX/loop experience  almost unacceptable, because the loop is not continuous, but it is still better than receiving youtube suggestions at the end of the played video. Honestly I don't think that it deserves a PR, but I'm preparing it anyway in such a way that you can decide if to accept it or not.

**Comment by chipsenkbeil** [comment]
@magomimmo, appreciate you taking the time to look into this. Merged the PR.

**Comment by magomimmo** [comment]
You're welcome! But I think that the `playlist` workaround to obtain a `loop` is very poor from the UX point of view, especially on ios mobiles. There should be something better around....when I'll find a better solution I let you know (but I'm not a front-ender at all).
