### ISSUE TITLE
Update font awesome?

### ISSUE THREAD

**Issue by inspiritana** [chipsenkbeil/grid-side#28]
I tried to add the snapchat icon to the footer bar, and thus figured out that it is not included. 
According to fontawesome.io, there are snapchat icons. Is it right to assume that the included font awesome version is just outdated?

If so, do you plan to update it in the future or am I supposed to do that myself?

**Comment by chipsenkbeil** [comment]
Most likely outdated. If you'd like to update it, feel free to create a pull request to do so. :)

**Comment by inspiritana** [comment]
Took me a while to figure out how, but I guess I just did my first pull request, yeah!

**Comment by chipsenkbeil** [comment]
Congratulations!
