### ISSUE TITLE
create and link to a demo of the theme

### ISSUE THREAD

**Issue by GeorgeWL** [chipsenkbeil/grid-side#38]
It feels a little silly not to, as it's hard to gauge whether it's worth installing without having some sort of preview

**Comment by chipsenkbeil** [comment]
@GeorgeWL, there used to be a hosted version of the theme on https://themes.gohugo.io, but I guess they stopped doing that? I could cobble something together and run it off of my personal server.

**Comment by GeorgeWL** [comment]
Seems many still have

Maybe they changed the method of doing it and didn't properly inform folks?  Cause yours isn't the only one with this issue.

**Comment by chipsenkbeil** [comment]
Closing this as the theme works under https://themes.gohugo.io/theme/grid-side
