### ISSUE TITLE
awesome icons not showing up

### ISSUE THREAD

**Issue by jlozadad** [chipsenkbeil/grid-side#39]
hello,

I created my page at https://jlozada2426.gitlab.io/blog//post/ and added links to the icons but, they are not showing up. Project stuff https://gitlab.com/jlozada2426/blog

**Comment by GraftJ** [comment]
In the [original single.html](https://github.com/chipsenkbeil/grid-side/blob/master/layouts/partials/homepage/single.html) file line 84, `{{ range .List }}` is the original code but it should be, `{{ range .list }}` with the l being lowercase.
